// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1) {
  return window['go']['core']['App']['CreateProject'](arg1);
}

export function GetAllControllers() {
  return window['go']['core']['App']['GetAllControllers']();
}

export function GetAllModels() {
  return window['go']['core']['App']['GetAllModels']();
}

export function LoadProject(arg1) {
  return window['go']['core']['App']['LoadProject'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['core']['App']['SaveProject'](arg1);
}
