// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateController(arg1) {
  return window['go']['core']['App']['CreateController'](arg1);
}

export function CreateModel(arg1) {
  return window['go']['core']['App']['CreateModel'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['core']['App']['CreateProject'](arg1);
}

export function CreateRoute(arg1) {
  return window['go']['core']['App']['CreateRoute'](arg1);
}

export function DeleteControllerByID(arg1) {
  return window['go']['core']['App']['DeleteControllerByID'](arg1);
}

export function DeleteModelByID(arg1) {
  return window['go']['core']['App']['DeleteModelByID'](arg1);
}

export function DeleteRouteByID(arg1) {
  return window['go']['core']['App']['DeleteRouteByID'](arg1);
}

export function GetAllControllers(arg1) {
  return window['go']['core']['App']['GetAllControllers'](arg1);
}

export function GetAllModels(arg1) {
  return window['go']['core']['App']['GetAllModels'](arg1);
}

export function GetAllRoutes(arg1) {
  return window['go']['core']['App']['GetAllRoutes'](arg1);
}

export function GetControllerByID(arg1) {
  return window['go']['core']['App']['GetControllerByID'](arg1);
}

export function GetModelByID(arg1) {
  return window['go']['core']['App']['GetModelByID'](arg1);
}

export function GetModelTypes() {
  return window['go']['core']['App']['GetModelTypes']();
}

export function GetRecentProjects() {
  return window['go']['core']['App']['GetRecentProjects']();
}

export function GetRouteByID(arg1) {
  return window['go']['core']['App']['GetRouteByID'](arg1);
}

export function Load() {
  return window['go']['core']['App']['Load']();
}

export function LoadProject(arg1) {
  return window['go']['core']['App']['LoadProject'](arg1);
}

export function Save() {
  return window['go']['core']['App']['Save']();
}

export function SaveCurrentProject() {
  return window['go']['core']['App']['SaveCurrentProject']();
}

export function SaveProject(arg1) {
  return window['go']['core']['App']['SaveProject'](arg1);
}

export function UpdateModel(arg1) {
  return window['go']['core']['App']['UpdateModel'](arg1);
}
