// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';
import {model} from '../models';

export function CreateProject(arg1:string):Promise<void>;

export function GetAllControllers():Promise<Array<controller.Controller>>;

export function GetAllModels():Promise<Array<model.Model>>;

export function LoadProject(arg1:string):Promise<void>;

export function SaveProject(arg1:string):Promise<void>;
