// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateController(arg1) {
  return window['go']['core']['App']['CreateController'](arg1);
}

export function CreateModel(arg1) {
  return window['go']['core']['App']['CreateModel'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['core']['App']['CreateProject'](arg1);
}

export function DeleteControllerByID(arg1) {
  return window['go']['core']['App']['DeleteControllerByID'](arg1);
}

export function DeleteModelByID(arg1) {
  return window['go']['core']['App']['DeleteModelByID'](arg1);
}

export function GetAllControllers() {
  return window['go']['core']['App']['GetAllControllers']();
}

export function GetAllModels() {
  return window['go']['core']['App']['GetAllModels']();
}

export function GetControllerByID(arg1) {
  return window['go']['core']['App']['GetControllerByID'](arg1);
}

export function GetModelByID(arg1) {
  return window['go']['core']['App']['GetModelByID'](arg1);
}

export function LoadProject(arg1) {
  return window['go']['core']['App']['LoadProject'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['core']['App']['SaveProject'](arg1);
}
